### ISSUE TITLE
DMCA Takedown notice for inclusion of galleria code

### ISSUE THREAD

**Issue by chrismcband** [PHPFrame/Mashine#43]
I received an email about this DMCA takedown for a company that is enforcing copyright on a premium theme. The offending folder is at: `/PHPFrame/Mashine/blob/master/public/assets/js/galleria/`

**Comment by chrismcband** [comment]
@lupomontero hi, it's been a long time. Did you get this notification too? I'm just going to follow https://help.github.com/articles/remove-sensitive-data to remove the files and remove them from whatever templates are using them.

**Comment by chrismcband** [comment]
I followed the guide and removed the galleria directory from all the git history, same with the forked version.

**Comment by lupomontero** [comment]
👍
